apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
  labels:
    purpose: test
spec:
  storageClassName: normal
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  hostPath:
    path: /etc/foo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  storageClassName: normal
  selector:
    matchLabels:
      purpose: test
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  automountServiceAccountToken: false
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 10; cat /etc/passwd > /etc/foo/passwd;sleep 3600;
    image: busybox
    name: busybox
    volumeMounts:
    - name: pwd
      mountPath: /etc/foo
  volumes:
  - name: pwd
    persistentVolumeClaim:
      claimName: pvc-1
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox2
spec:
  automountServiceAccountToken: false
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 3600;
    image: busybox
    name: busybox
    volumeMounts:
    - name: pwd
      mountPath: /etc/foo
      readOnly: true
  volumes:
  - name: pwd
    persistentVolumeClaim:
      claimName: pvc-1
