apiVersion: v1
data:
  password: bXlwYXNz
kind: Secret
metadata:
  name: mysecret
---
apiVersion: v1
data:
  MESSAGE: SEVMTE8gUkFKRVNI
  WHOAMI: UkFKRVNIIFNVTkRBUkFN
kind: Secret
metadata:
  creationTimestamp: null
  name: mysecret2

---

