apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-env
spec:
  containers:
  - image: nginx
    name: nginx
    envFrom:
    - configMapRef:
        name: config    
  dnsPolicy: ClusterFirst
