apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  containers:
    - name: busybox
      image: busybox:1.34.1
      command:
        - "env"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  restartPolicy: Never
