apiVersion: v1
kind: Pod
metadata:
  name: busybox-multicontainer
spec:
  restartPolicy: Never
  containers:
    - name: busybox-1
      image: busybox
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      args:
        - /bin/sh
        - -c
        - echo hello; sleep 3600
    - name: busybox-2
      image: busybox
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      args:
        - /bin/sh
        - -c
        - echo hello; sleep 3600
