apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  conf: |-
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  65;

        upstream jsonplaceholder {
            server 127.0.0.1:3000;
        }

        server {
            listen 80;

            location / {
                proxy_pass         http://jsonplaceholder;
                proxy_redirect     off;
            }
        }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: mc-pod
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-pod
spec:
  selector:
    matchLabels:
      app: mc-pod
  template:
    metadata:
      labels:
        app: mc-pod
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: conf
        - name: jsonplaceholder
          image: svenwal/jsonplaceholder
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
