apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
    fsGroup: 3000
  volumes:
  - name: data
    emptyDir: {}
  containers:
  - image: nginxinc/nginx-unprivileged #non-root image
    name: nginx
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: data
      mountPath: /var/data/volcontent
      readOnly: true
  initContainers:
  - name: bb
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Hello Rajesh!' > /data/greet.txt"]
    volumeMounts:
    - name: data
      mountPath: /data 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
