apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ng1
  name: ng1
spec:
  containers:
    - image: nginx
      name: ng1
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Never

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ng2
  name: ng2
spec:
  containers:
    - image: nginx
      name: ng2
      resources:
        requests:
          memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Never

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ng3
  name: ng3
spec:
  containers:
    - image: nginx
      name: ng3
  dnsPolicy: ClusterFirst
  restartPolicy: Never
