apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: linux
  name: linux
  namespace: test
spec:
  containers:
    - command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "100M", "--vm-hang", "1"]
      image: polinux/stress
      name: linux
      resources:
        requests:
          cpu: "8500m"
          # memory: 11Gi
          memory: 128M
        limits:
          cpu: "10000m"
          memory: 15Gi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
