apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: operators.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
                age:
                  type: integer
  scope: Namespaced
  names:
    plural: operators
    singular: operator
    kind: Operator 
    shortNames:
    - op
---
apiVersion: stable.example.com/v1
kind: Operator 
metadata:
  name: abc-op
spec:
  email: tzrajesh7@gmail.com
  name: Rajesh Sundaram
  age: 28
