apiVersion: batch/v1
kind: Job
metadata:
  name: bb
spec:
  activeDeadlineSeconds: 30
  parallelism: 1
  completions: 5 
  template:
    spec:
      containers:
      - command:
        - /bin/sh 
        - -c 
        - 'echo hello;sleep 2;echo world'
        image: busybox
        name: bb
      restartPolicy: Never
