apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - env 
        image: perl
        name: pi
      restartPolicy: OnFailure
