apiVersion: batch/v1
kind: CronJob
metadata:
  name: printer
spec:
  suspend: false
  startingDeadlineSeconds: 17
  jobTemplate:
    metadata:
      name: printer
    spec:
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox
            name: printer
          restartPolicy: OnFailure
  schedule: '* * * * *'
