apiVersion: v1
data:
  fluent.conf: |
    <source>
      @type http
      port 9880
      bind 0.0.0.0
    </source>

    <match **>
      @type stdout
    </match>
kind: ConfigMap
metadata:
  name: fluentd-cm
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: fluentd
  name: fluentd
spec:
  containers:
  - image: nicolaka/netshoot
    name: client
    command: ["bash", "-c", "sleep 10s; while true; do curl -X POST -d 'json={\"json\":\"message\"}' http://127.0.0.1:9880/sample.test; sleep 1; done"]
  - image: fluent/fluentd:edge-debian
    name: fluentd
    ports:
    - containerPort: 9880
    volumeMounts:
    - name: fconfig
      mountPath: /fluentd/etc/
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: fconfig
    configMap:
      name: fluentd-cm
---
      

