apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    webapp-color: green
  name: webapp-color
spec:
  containers:
  - image: nginx
    name: webapp-color
    env:
    - name: APP_COLOR
      value: green
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
