apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mail-server-inmem
  region: ap-northeast-1

nodeGroups:
  - name: g1
    instanceType: m5.xlarge
    minSize: 1
    maxSize: 2
    desiredCapacity: 2

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
