apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: pvt-img-puller
imagePullSecrets:
  - name: pvt-reg
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
spec:
  serviceAccountName: pvt-img-puller
  containers:
  - image: tzrajesh7/test-xyz-abc
    name: test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
