apiVersion: v1
data:
  key1: dmFsdWU0
kind: Secret
metadata:
  creationTimestamp: null
  name: another-secret
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-secret
  name: nginx-secret
spec:
  containers:
  - image: nginx
    name: nginx-secret
    resources: {}
    env:
    - name: COOL_VARIABLE
      valueFrom:
        secretKeyRef:
          key: key1
          name: another-secret 
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
