apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: restrictedservice
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: production
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-a
  name: app-a
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-a
    spec:
      serviceAccountName: restrictedservice
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
