apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/KDSP00101/data
  storageClassName: standard
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: node
            operator: In
            values:
            - data-node  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: my-storage-app
  name: nginx-mount
spec:
  containers:
  - image: nginx
    name: nginx-mount
    resources: {}
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: task-pv-claim
