apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: counter
  name: counter
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - while true; do echo $(date);sleep 1s;done
    image: busybox
    name: counter
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
