apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 5
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      #exec:
      #  command:
      #  - ls 
      #  - /usr/share/nginx/html
  dnsPolicy: ClusterFirst
  restartPolicy: Always
