apiVersion: v1
kind: Namespace
metadata:
  name: qa
---
apiVersion: v1
kind: Namespace
metadata:
  name: rajesh
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bb
  name: bb
  namespace: test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bb
  template:
    metadata:
      labels:
        app: bb
    spec:
      containers:
      - command:
        - sh
        - -c
        - mkdir -p /usr/rajesh;sleep 60; rm -rf /usr/rajesh;
        image: busybox
        name: bb
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          exec:
            command:
            - sh
            - -c
            - ls /usr/rajesh
      dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bb
  name: bb
  namespace: qa
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 60; echo "bb-exits";
    image: busybox
    name: bb
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      exec:
        command:
        - sh
        - -c
        - ls /usr/rajesh
  dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: production
spec:
  containers:
  - image: nginx
    name: nginx
    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 5
      httpGet:
        path: /
        port: 80
        scheme: HTTP
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: rajesh
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          exec:
            command:
            - sh
            - -c
            - ls /usr/rajesh/blawblaw
          
