apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-bb
  name: multi-bb
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    name: multi-bb-1

  - command:
    - /bin/sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    name: multi-bb-2
  dnsPolicy: ClusterFirst
  restartPolicy: Never
