apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-liveness
  name: nginx-liveness
spec:
  containers:
  - image: nginx
    name: nginx-liveness
    livenessProbe:
      httpGet:
        path: /
        port: 80
    readinessProbe:
      exec:
        command: ["ls"]
      periodSeconds: 2
      initialDelaySeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-failes
  name: nginx-failes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-failes
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-failes
    spec:
      containers:
      - image: nginx
        name: nginx-failes-live
        livenessProbe:
          httpGet:
            path: /abc
            port: 80
        readinessProbe:
          exec:
            command: ["ls"]
          periodSeconds: 2
          initialDelaySeconds: 5
