apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rq-nginx
  name: rq-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rq-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rq-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
          requests:
            cpu: "500m"
            memory: "500Mi"

