apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bb
  name: bb
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: accelerator 
            operator: In
            values:
            - nvidia-tesla-p100
  containers:
  - command:
    - sh
    - -c
    - sleep 60
    image: busybox
    name: bb
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
