apiVersion: v1
kind: Namespace
metadata:
  name: alb-ingress-cntl-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: alb-ingress-cntl-test
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsonplaceholder
  namespace: alb-ingress-cntl-test
spec:
  selector:
    matchLabels:
      app: jsonplaceholder
  template:
    metadata:
      labels:
        app: jsonplaceholder
    spec:
      containers:
        - name: json
          image: svenwal/jsonplaceholder
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: alb-ingress-cntl-test
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jsonplaceholder-svc
  namespace: alb-ingress-cntl-test
spec:
  type: NodePort
  selector:
    app: jsonplaceholder
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: common-ingress
  namespace: alb-ingress-cntl-test
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    # alb.ingress.kubernetes.io/certificate-arn: <ACM CERTIFICATE ARN>
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
spec:
  rules:
    - host: nginx.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-svc
                port:
                  number: 80
    - host: json.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jsonplaceholder-svc
                port:
                  number: 80
