apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bb
  name: bb
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - i=1;while true;do echo "$i => $(date)";i=$(expr $i + 1);sleep 1;done
    image: busybox
    name: bb
  dnsPolicy: ClusterFirst
  restartPolicy: Never
