apiVersion: v1
kind: Service
metadata:
  labels:
    abc: ngixn
  name: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30950
  selector:
    app: hell
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    abc: ngixn
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hell
  template:
    metadata:
      labels:
        app: hell
    spec:
      # kubectl label nodes kind-worker node-purpose=nginx
      nodeSelector:
        node-purpose: nginx
      containers:
      - image: nginxdemos/hello:plain-text
        name: nginx
        ports:
        - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always
